INSERT INTO `bacteria` (`ID_BACTERIA`, `NOM_BACTERIA`) VALUES
(2, 'NO APLICA'),
(5, 'VACIO'),
(6, 'NO DETECTA '),
(7, 'CONTAMINADO'),
(9, 'ENTEROCOCCUS FAECIUM'),
(10, 'ENTEROCOCCUS FAECALIS'),
(18, 'CONTAMINADO'),
(19, 'STAPHYLOCOCCUS AUREUS'),
(20, 'ENTEROBACTER CLOACAE COMPLEX'),
(50, 'Organism'),
(51, 'Escherichia coli'),
(52, 'Klebsiella pneumoniae ss. pneumoniae'),
(53, 'Staphylococcus aureus ss. aureus'),
(55, 'Pseudomonas aeruginosa'),
(56, 'Enterococcus faecalis'),
(57, 'Enterobacter cloacae'),
(58, 'Proteus mirabilis'),
(59, 'Acinetobacter baumannii'),
(60, 'Candida albicans'),
(61, 'Streptococcus agalactiae'),
(62, 'Staphylococcus haemolyticus'),
(63, 'Staphylococcus hominis ss. hominis'),
(64, 'Serratia marcescens'),
(65, 'Klebsiella oxytoca'),
(66, 'Morganella morganii ss. morganii'),
(67, 'Enterobacter aerogenes'),
(68, 'Candida tropicalis'),
(69, 'Stenotrophomonas maltophilia'),
(70, 'Citrobacter freundii'),
(71, 'Enterococcus faecium'),
(72, 'Staphylococcus warneri'),
(73, 'Burkholderia cepacia'),
(74, 'Candida parapsilosis'),
(75, 'Malassezia sp.'),
(76, 'Streptococcus pneumoniae'),
(77, 'Staphylococcus capitis ss. capitis'),
(78, 'Staphylococcus saprophyticus ss. saprophyticus'),
(79, 'Citrobacter koseri (diversus)'),
(80, 'Aeromonas hydrophila'),
(81, 'Pseudomonas putida'),
(82, 'Streptococcus mitis'),
(83, 'Streptococcus viridans, alpha-hem.'),
(84, 'Proteus rettgeri'),
(85, 'Acinetobacter lwoffii'),
(86, 'Staphylococcus lugdunensis'),
(87, 'Pseudomonas fluorescens'),
(88, 'Trichophyton rubrum'),
(89, 'Candida glabrata'),
(90, 'Trichosporon asahii'),
(91, 'Campylobacter lari'),
(92, 'Moraxella (Branh.) catarrhalis'),
(93, 'Trichophyton mentagrophytes'),
(94, 'Gardnerella vaginalis'),
(95, 'Klebsiella pneumoniae ss. ozaenae'),
(96, 'Proteus vulgaris'),
(97, 'Rhodotorula mucilaginosa'),
(98, 'Klebsiella sp.'),
(99, 'Raoultella planticola'),
(100, 'Streptococcus pyogenes'),
(101, 'Proteus sp.'),
(102, 'Salmonella sp.'),
(103, 'Staphylococcus, coagulase negative'),
(104, 'NO DETECTA'),
(105, 'Haemophilus influenzae'),
(106, 'Pantoea agglomerans'),
(107, 'Serratia liquefaciens'),
(108, 'Aspergillus flavus'),
(109, 'Staphylococcus sp.'),
(110, 'Streptococcus sp.'),
(111, 'Acinetobacter sp.'),
(112, 'Enterobacter sp.'),
(113, 'Geotrichum candidum'),
(114, 'Proteus penneri'),
(115, 'Pseudomonas sp.'),
(116, 'Microsporum canis var. canis'),
(117, 'Sphingomonas paucimobilis'),
(118, 'Staphylococcus caprae'),
(119, 'Staphylococcus sciuri ss. lentus'),
(120, 'Citrobacter braakii'),
(121, 'Pseudomonas stutzeri'),
(122, 'Raoultella ornitholytica'),
(123, 'Staphylococcus sciuri ss. sciuri'),
(124, 'Cryptococcus neoformans'),
(125, 'Scedosporium apiospermum'),
(126, 'Achromobacter sp.'),
(127, 'Aspergillus niger'),
(128, 'Candida krusei'),
(129, 'Candida sp.'),
(130, 'Corynebacterium sp. (diphtheroids)'),
(131, 'Serratia fonticola'),
(132, 'Chryseomonas luteola'),
(133, 'Corynebacterium sp.'),
(134, 'Enterococcus sp.'),
(135, 'Fusarium solani'),
(136, 'Kocuria kristinae'),
(137, 'Streptococcus anginosus'),
(138, 'Streptococcus sanguinis'),
(139, 'Trichosporon sp.'),
(140, 'Acinetobacter haemolyticus'),
(141, 'Aeromonas sobria'),
(142, 'Bacillus sp.'),
(143, 'Geotrichum sp.'),
(144, 'Haemophilus sp.'),
(145, 'Hafnia alvei'),
(146, 'Kocuria rosea'),
(147, 'Providencia stuartii'),
(148, 'Acinetobacter junii'),
(149, 'Aeromonas sp.'),
(150, 'Aspergillus fumigatus'),
(151, 'Candida ciferrii'),
(152, 'Enterobacter asburiae'),
(153, 'Enterococcus avium'),
(154, 'Enterococcus gallinarum'),
(155, 'Staphylococcus cohnii ss. cohnii'),
(156, 'Staphylococcus simulans'),
(157, 'Staphylococcus xylosus'),
(158, 'Streptococcus dysgalactiae ss. dysgalactiae'),
(159, 'Candida famata'),
(160, 'Candida guilliermondii'),
(161, 'Candida lusitaniae'),
(162, 'Cladosporium sp.'),
(163, 'Enterococcus hirae'),
(164, 'Achromobacter xylosoxidans ss. denitrificans'),
(165, 'Enterococcus casseliflavus'),
(166, 'Enterococcus raffinosus'),
(167, 'Fusarium sp.'),
(168, 'Micrococcus luteus'),
(169, 'Morganella morganii ss. sibonii'),
(170, 'Pantoea sp.'),
(171, 'Serratia sp.'),
(172, 'Shigella sonnei'),
(173, 'Staphylococcus auricularis'),
(174, 'Streptococcus dysgalactiae ss. equisimilis'),
(175, 'Streptococcus gordonii'),
(176, 'Streptococcus salivarius'),
(177, 'Streptococcus thoraltensis'),
(178, 'Streptococcus, beta-haem. Group B'),
(179, 'Acidaminococcus fermentans'),
(180, 'Bacteroides fragilis'),
(181, 'Blastoschizomyces capitatus'),
(182, 'Enterobacter gergoviae'),
(183, 'Enterococcus durans'),
(184, 'Escherichia fergusonii'),
(185, 'Flavimonas oryzihabitans'),
(186, 'Micrococcus sp.'),
(187, 'Rhizopus sp.'),
(188, 'Serratia odorifera'),
(189, 'Serratia plymuthica'),
(190, 'Serratia rubidaea'),
(191, 'Shigella sp.'),
(192, 'Staphylococcus chromogenes'),
(193, 'Streptococcus constellatus'),
(194, 'Streptococcus gallolyticus ss. pasteurianus'),
(195, 'Streptococcus milleri'),
(196, 'Streptococcus uberis'),
(197, 'Trichosporon mucoides'),
(198, 'Achromobacter xylosoxidans ss. xylosoxidans'),
(199, 'Acidovorax sp.'),
(200, 'Alcaligenes faecalis (odorans)'),
(201, 'Aspergillus terreus'),
(202, 'Candida dubliniensis'),
(203, 'Candida rugosa'),
(204, 'Chromobacterium sp.'),
(205, 'Chryseobacterium indologenes'),
(206, 'Citrobacter amalonaticus'),
(207, 'Citrobacter farmeri'),
(208, 'Curvularia sp.'),
(209, 'Elizabethkingia meningosepticum'),
(210, 'Escherichia coli O149'),
(211, 'Granulicatella adiacens'),
(212, 'Lactobacillus sp.'),
(213, 'Legionella sp.'),
(214, 'Pasteurella multocida ss. multocida'),
(215, 'Salmonella enterica ss. enterica (Subgroup I)'),
(216, 'Salmonella Typhi'),
(217, 'Staphylococcus equorum'),
(218, 'Staphylococcus gallinarum'),
(219, 'Staphylococcus intermedius'),
(220, 'Staphylococcus pseudintermedius'),
(221, 'Streptococcus bovis I'),
(222, 'Streptococcus intermedius'),
(223, 'Streptococcus parasanguinis'),
(224, 'Trichosporon beigelii'),
(225, 'Yersinia enterocolitica'),
(226, 'Acholeplasma sp.'),
(227, 'Acidaminococcus sp.'),
(228, 'Acinetobacter calcoaceticus'),
(229, 'Actinomyces sp.'),
(230, 'Aerococcus viridans'),
(231, 'Aeromonas caviae'),
(232, 'Arcanobacterium haemolyticum'),
(233, 'Aureobasidium sp.'),
(234, 'Bacteroides sp.'),
(235, 'Bordetella bronchiseptica'),
(236, 'Bordetella hinzii'),
(237, 'Brevundimonas vesicularis'),
(238, 'Burkholderia cepacia complex'),
(239, 'Burkholderia gladioli'),
(240, 'Candida kefyr (pseudotropicalis)'),
(241, 'Candida pelliculosa'),
(242, 'Capnocytophaga sp.'),
(243, 'Chrysosporium sp.'),
(244, 'Citrobacter sedlakii'),
(245, 'Citrobacter sp.'),
(246, 'Comamonas terrigena'),
(247, 'Corynebacterium amycolatum'),
(248, 'Corynebacterium jeikeium'),
(249, 'Corynebacterium minutissimum'),
(250, 'Corynebacterium striatum'),
(251, 'Cupriavidus pauculus'),
(252, 'Deinococcus sp.'),
(253, 'Dermacoccus nishinomiyaensis'),
(254, 'Edwardsiella hoshinae'),
(255, 'Entamoeba coli'),
(256, 'Enterobacter cancerogenus (taylorae)'),
(257, 'Enterobacter dissolvens'),
(258, 'Escherichia coli (alkalescens-dispar)'),
(259, 'Escherichia hermannii'),
(260, 'Escherichia sp.'),
(261, 'Escherichia vulneris'),
(262, 'Fusarium dimerum'),
(263, 'Gemella morbillorum'),
(264, 'Gemella sp.'),
(265, 'Geotrichum penicillatum'),
(266, 'Gordona bronchialis'),
(267, 'Haemophilus parahaemolyticus'),
(268, 'Haemophilus parainfluenzae'),
(269, 'Helicobacter fennelliae (CLO-2)'),
(270, 'Kluyvera ascorbata'),
(271, 'Kluyvera cryocrescens'),
(272, 'Kluyvera intermedia'),
(273, 'Kluyvera sp.'),
(274, 'Kocuria sp.'),
(275, 'Kocuria varians'),
(276, 'Lactococcus garvieae'),
(277, 'Leclercia adecarboxylata'),
(278, 'Leuconostoc pseudomesenteroides'),
(279, 'Listeria monocytogenes'),
(280, 'Micropolyspora sp.'),
(281, 'Microsporum audouinii'),
(282, 'Microsporum gypseum'),
(283, 'Moraxella sp.'),
(284, 'Morganella sp.'),
(285, 'Mycobacterium confluentis'),
(286, 'Neisseria elongata ss. elongata'),
(287, 'Neisseria meningitidis, serogroup a'),
(288, 'Other'),
(289, 'Peptostreptococcus sp.'),
(290, 'Providencia alcalifaciens'),
(291, 'Providencia sp.'),
(292, 'Pseudomonas alcaligenes'),
(293, 'Rhinocladiella sp.'),
(294, 'Rhizomucor sp.'),
(295, 'Rickettsia conorii'),
(296, 'Salmonella enterica ss. salamae (Subgroup II)'),
(297, 'Salmonella Group 51 (O:51)'),
(298, 'Salmonella Manhattan'),
(299, 'Salmonella Saintpaul'),
(300, 'Scopulariopsis sp.'),
(301, 'Shewanella alga'),
(302, 'Shewanella putrefaciens'),
(303, 'Shewanella sp.'),
(304, 'Sphingomonas sp.'),
(305, 'Stachybotrys sp.'),
(306, 'Stenotrophomonas sp.'),
(307, 'Streptococcus acidominimus'),
(308, 'Streptococcus alactolyticus'),
(309, 'Streptococcus infantarius'),
(310, 'Streptococcus pleomorphus'),
(311, 'Streptococcus, beta-haem. Group A'),
(312, 'Streptococcus, beta-haemolytic'),
(313, 'Streptococcus, beta-haemolytic (not Group A)'),
(314, 'Trichophyton tonsurans'),
(315, 'Trichophyton yaoundei'),
(316, 'Tricothecium roseum'),
(317, 'Tricothecium sp.'),
(318, 'Yersinia intermedia');
